version: '3.7'

services:
  client:
    container_name: pathondb/client
    build: ../client
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - REACT_APP_API_URL=http://localhost:80
    depends_on:
      - server
  server:
    build: .
    environment:
        STAGE: "PRODUCTION"
    restart: always
    ports:
        - "5000:80"